### ISSUE TITLE
USER STORY: Setup and Install Django

### ISSUE THREAD

**Issue by neil314159** [neil314159/portfolio-project-4#11]
As a developer, I can set up django and the necessary software packages, so that I can deploy the site and begin development

## Tasks
- [x] Create Githib repository using the Code Institute template
- [x] Create Gitpod workspace
- [x] install psycopg2
- [x] install cloudinary library
- [x] install gunicorn
- [x] Create requirements.txt file
