### ISSUE TITLE
USER STORY: Set up environmental variables securely

### ISSUE THREAD

**Issue by neil314159** [neil314159/portfolio-project-4#12]
As a **developer**, I want **to set up the secret keys and database variable in a secure manner**, so that **they are kept hidden when deployed and not accidentally exposed through github**

## Tasks
- [x] Create env.py file to store variable
- [x] Link to django settings file
- [x] Add env.py to gitignore so it is not commited
- [x] Add secret key and database variables to heroku through website interface
