### ISSUE TITLE
USER STORY: Deploy to heroku

### ISSUE THREAD

**Issue by neil314159** [neil314159/portfolio-project-4#13]
As a **developer**, I want **to ensure that the deployment pipeline is functioning**, so that **I can commence development on the project and test on heroku as well as the local environment**

## Tasks
- [x] Create a new heroku app through the CLI or web interface
- [x] Create a postgres database on heroku
- [x] Configure the settings.py file to point to correct database depending on local or production environment
- [x] sign up for cloudinary API key and add details to settings.py
