### ISSUE TITLE
USER STORY: Create a user profile

### ISSUE THREAD

**Issue by neil314159** [neil314159/portfolio-project-4#14]
As a **user**, I can **create a new account on the Book Barn website**, so that **I have the permissions required to publish my own reviews on the site**

## Acceptance Criteria
- Acceptance Criteria 1
	**Given** I am a new user without an account
	**When** I visit the homepage
	**Then** I can see a button that allows me to register a new account
- Acceptance Criteria 2
	**Given** I clicked on the button register and I am on the registration form
	**When** I enter my details such as name password and email address
	**Then** I am automatically signed in with my new account
- Acceptance Criteria 3
	**Given** that I am registered on the site
	**When** I am logged in
	**Then** I no longer am presented with a button to register or login

## Tasks
- [x] Create user model
- [x] Add a link to the home page and nav bar to let users register for a new account
- [x] Hide this link once users are logged in
- [x] Install crispy forms to style new form
- [x] Add form to allow for user registration
