### ISSUE TITLE
USER STORY: Update user profile

### ISSUE THREAD

**Issue by neil314159** [neil314159/portfolio-project-4#16]
As a **user**, I can **view my own profile page and edit my username**, so that **I can change the name displayed on my reviews that is displayed to other users and site visitors**

## Acceptance Criteria
- Acceptance Criteria 1
	**Given** I am logged into the site and on my own profile page
        **Then** I can see a link beside my displayed username to edit it
	**When** I click this link
	**Then** I am shown a form which allows me to change the username
- Acceptance Criteria 2
	**Given** I have changed my username on the form
	**When** I click submit on the form
	**Then** i See a message confirming my username has been changed and I can see my updated username on the profile page
- Acceptance Criteria 3
	**Given** that I am not logged into the site
	**When** I try to access a user profile page through a URL
	**Then** I am redirected to the login page

## Tasks
- [ ] add a username display to the profile page
- [ ] add an edit button and a form to change the username
- [ ] display a message on successful username change
- [ ] require a login for these pages to make sure no one else can edit or view profiles other than their own

**Comment by neil314159** [comment]
Profile page has been changed in layout and design to allow for account and password management, but not username changes
