### ISSUE TITLE
USER STORY: Delete user profile

### ISSUE THREAD

**Issue by neil314159** [neil314159/portfolio-project-4#17]
As a **user**, I can **delete my own account**, so that **I can remove my information and content from the site if I desire**

## Acceptance Criteria
- Acceptance Criteria 1
	**Given** that I am registered on the site and logged in
	**When** I click on my profile page
	**Then** I can see a button allowing me to delete my account
- Acceptance Criteria 2
	**Given** that I click the button to delete my account
	**When** form is presented
	**Then** I can confirm that I wish to delete the account or go back if I prefer
- Acceptance Criteria 3
	**Given** that I confirmed my wish to delete the account
	**When** the account is successfully deleted
	**Then** I am logged out and returned to the home page with a message confirming my account deletion
- Acceptance Criteria 4
	**Given** that I am logged into my account
	**When** I attempt to delete another account through a URL path
	**Then** I am redirected to the home page

## Tasks
- [x] add a button to the profile page allowing the user to delete their account
- [x] add a form which requires confirmation of this request
- [x] add a message confirming the deletion and return the user to the home page
- [x] require the user to be logged in and make sure the deletion request comes from the same user
- [x] redirect an illegal request to delete to the home page
