### ISSUE TITLE
USER STORY: Change user password

### ISSUE THREAD

**Issue by neil314159** [neil314159/portfolio-project-4#18]
As a **user**, I can **change my password**, so that **my account remains secure**

## Acceptance Criteria
- Acceptance Criteria 1
	**Given** that I am logged in to my account
	**When** I click on my profile page
	**Then** I can see a link allowing me to change my password
- Acceptance Criteria 2
	**Given** I have clicked the change password link
	**When** I change my password
	**Then** I can see a message confirming the change
- Acceptance Criteria 3
	**Given** that I attempt to change my password with the link
	**When** the new passwords do not match or do not meet security requirements
	**Then** I am prevented from changing my password until these requirements are met

## Tasks
- [x] Add a link to the profile page allowing a password change
- [x] Create a new form allowing the suer to input their new password
- [x] Validate the new data and update the user entry in the database
- [x] Present a message to the user confirming a successful password change
