### ISSUE TITLE
USER STORY: Reset user password

### ISSUE THREAD

**Issue by neil314159** [neil314159/portfolio-project-4#19]
As a **user**, I can **reset my password**, so that **can access my account if my password is forgotten**

## Acceptance Criteria
- Acceptance Criteria 1
	**Given** that I attempt to log in to the site
	**When** I enter an incorrect password
	**Then** I can click a link to reset my password
- Acceptance Criteria 2
	**Given** that I click on the password reset link
	**When** I confirm my email address
	**Then** I am sent instructions and a link via email which allows me to reset my password
- Acceptance Criteria 3
	**Given** I have clicked the reset link and reset my password
	**When** I attempt to log in
	**Then** my new password should allow me to log in

## Tasks
- [x] Add a link to the login page for resetting the password
- [x] set up email validation for new users
- [x] install allauth package
- [x] verify that password reset form has been created and is working
- [x] set up SMTP credentials to allow outgoing mail from django
