### ISSUE TITLE
USER STORY: Authenticate user login/logout

### ISSUE THREAD

**Issue by neil314159** [neil314159/portfolio-project-4#20]
As a **user**, I can **log and and out of the site**, so that **my personal details and content are kept secure**

## Acceptance Criteria
- Acceptance Criteria 1
	**Given** that I am not logged in
	**When** I click the login button
	**Then** I can enter my details and log into the site with the correct name and password
- Acceptance Criteria 2
	**Given** that I am logged in to the site
	**When** I click the logout button in the navbar
	**Then** my account is signed out and I am redirected to the home page

## Tasks
- [x] configure allauth authentication software
- [x] create a login form and connect to the user profile model
- [x] ensure that the form validation is working correctly
- [x] place login/logout button in navbar that accurately reflects user state
