### ISSUE TITLE
USER STORY: Social login

### ISSUE THREAD

**Issue by neil314159** [neil314159/portfolio-project-4#22]
As a **user**, I can **sign into the site using another account such as Google or Facebook**, so that **do not have to sign up for a new account and remember another password**

## Acceptance Criteria
- Acceptance Criteria 1
	**Given** that I have clicked on the Register link on the site
	**When** the signup form is presented
	**Then** I have option to log in to the site using another social account such as Google
- Acceptance Criteria 2
	**Given** that I have signed in using a social account
	**When** the login process is complete
	**Then** I am redirected to the home page and given full access to the site like any other user

## Tasks
- [ ] Configure allauth software package to allow various social logins such as facebook/google
- [ ] set up API keys for each service to validate login form
- [ ] test access with a variety of social login accoounts from different providers
- [ ] check that social logins and registered users are presented with the same access to the site
