### ISSUE TITLE
USER STORY: Add/remove books from wishlist

### ISSUE THREAD

**Issue by neil314159** [neil314159/portfolio-project-4#23]
As a **user**, I can **click on a like button on each review**, so that **the book is saved to my wishlist and I can keep track of new books to read**

## Acceptance Criteria
- Acceptance Criteria 1
	**Given** that I am logged into the site and viewing a review
	**When** I click on the like button
	**Then** the book is added to my wishlist and the button changes state to reflect this
- Acceptance Criteria 2
	**Given** that I am on the same page and have added the book to my wishlist
	**When** I click the like button again
	**Then** the book is removed from my wishlist, the button state reflects this and I see a message confirming this

## Tasks
- [x] create a wishlist model
- [x] add a button the review page allowing the book to be added to the list
- [ ] set the button to visually change state to reflect if the book has been added or removed

**Comment by neil314159** [comment]
Due to design of wishlist model which includes creation date, read/unread status and potential multiple entries for the same book, toggling state for removing from the review page is difficult and will be deferred to future development
