### ISSUE TITLE
USER STORY: View wishlist on profile page

### ISSUE THREAD

**Issue by neil314159** [neil314159/portfolio-project-4#24]
As a **user**, I can **click on my wishlist link**, so that **I can see at a glance a list of all the books on my wishlist**

## Acceptance Criteria
- Acceptance Criteria 1
	**Given** that I am logged in to the site
	**When** I click the wishlist link in the nav bar
	**Then** I am presented with a list of all books I have saved in my list
- Acceptance Criteria 2
	**Given** that I am viewing my list of saved book
	**When** I click the remove link beside any entry
	**Then** the book is removed from the list and a confirmation message is displayed

## Tasks
- [x] add a wishlist link to the navbar
- [x] create a new page of search results displaying a query from the database showing a list of all books saved by the user
- [x] add a button beside each entry allowing the book to be removed

**Comment by neil314159** [comment]
Wishlist has been moved to its own page with a link in the navbar for logged in users
