### ISSUE TITLE
USER STORY: Moderation for comments in admin panel

### ISSUE THREAD

**Issue by neil314159** [neil314159/portfolio-project-4#27]
As a **site owner**, I can **view all comments on the site through the admin interface and delete them if required**, so that **inappropriate comments are not publicly displayed**

## Acceptance Criteria
- Acceptance Criteria 1
	**Given** that the site owner logs into the admin panel
	**When** the comments section is selected
	**Then** all site comments are displayed chronologically
- Acceptance Criteria 2
	**Given** that an inappropriate comment has been left on the site
	**When** the site owner deletes it using the admin panel
	**Then** the comment is removed from the publicly displayed review on the site

## Tasks
- [ ] add comments model to admin settings
- [ ] format table to display the comments in the admin panel
- [ ] enable searching and deletion of all comments by the site owner
