### ISSUE TITLE
USER STORY: Allow users to manage comments on their own reviews

### ISSUE THREAD

**Issue by neil314159** [neil314159/portfolio-project-4#28]
As a **user**, I can **delete comments left by other users on my own reviews**, so that **inappropriate comments are not displayed next to content I have written and the administrative burden is lightened for the site owner**

## Acceptance Criteria
- Acceptance Criteria 1
	**Given** that I am logged in and viewing a review I have written
	**When** I examine the comments left on the article
	**Then** I am presented with a delete button for each comment next to the comment itself
- Acceptance Criteria 2
	**Given** that I click the delete button for a particular comment
	**Then** the comment is deleted and a confirmation message displayed
- Acceptance Criteria 3
	**Given** that I am viewing a review page that I did not author
	**When** I look at the comments on the page
	**Then** I will not see a button to delete each comment

## Tasks
- [x] add a delete button for all comments left on a review page
- [x] only display this button to the author of the page or the site owner by checking permissions in the database
- [x] add a confirmation message when the comment has been removed
