### ISSUE TITLE
USER STORY: Sitewide search

### ISSUE THREAD

**Issue by neil314159** [neil314159/portfolio-project-4#29]
As a **user**, I can **type text into the search box in the navigation bar**, so that **I can find matching text in any reviews on the site**

## Acceptance Criteria
- Acceptance Criteria 1
	**Given** that i type text into the search box in the navigation bar
	**When** I click search button or hit return on the keyboard
	**Then** I am presented with a list of articles with text matching my search term
- Acceptance Criteria 2
	**Given** I am viewing a list of search results
	**When** I click on the title of a book review
	**Then** I am brought to the page displaying that individual book review
- Acceptance Criteria 3
	**Given** that there may be many search results presented
	**When** I view the list of results
	**Then** they will be split into multiple pages with navigation buttons underneath

## Tasks
- [x] Add a search box to the navbar template
- [x] create a search results page and add to the URLS file
- [x] create a query based on inputted text, run against the database and present results on search page
- [x] add pagination for search results

**Comment by neil314159** [comment]
Search pagination was implemented with help of:
https://stackoverflow.com/questions/68155106/filter-class-based-view-listview-that-has-pagination
since the query needs to be passed in the string
