### ISSUE TITLE
USER STORY: AJAX live search

### ISSUE THREAD

**Issue by neil314159** [neil314159/portfolio-project-4#30]
As a **user**, I can **type text into the search box in the navigation bar**, so that **I see a continuously updated set of search results as I type**

## Acceptance Criteria
- Acceptance Criteria 1
	**Given** that I type a search term into the search box in the nav bar
	**When** more than three characters have been entered
	**Then** a continuously updated list of search results appears below the search box
- Acceptance Criteria 2
	**Given** that the list of results appears below the search box
	**When** an individual result is clicked on 
	**Then** the user is redirected to the page for that book review

## Tasks
- [ ] Add jQuery code to the navbar template to capture search text box contents
- [ ] create a function to return search results from database
- [ ] set time delay for partial matches eg 500ms so that the user may type before the results are updated and presented
- [ ] using javascript update the search results below the text search box in a drop down menu
- [ ] link those results to an individual URL for each article
