### ISSUE TITLE
USER STORY: Category-based view

### ISSUE THREAD

**Issue by neil314159** [neil314159/portfolio-project-4#31]
As a **user**, I can **select a category from a drop-down menu in the navbar**, so that **I can view books that interest me the most in a particular genre**

## Acceptance Criteria
- Acceptance Criteria 1
	**Given** that I click the category button in the navbar
	**When** a genre is selected
	**Then** I am presented with a search results page showing all book reviews that match the genre
- Acceptance Criteria 2
	**Given** that I am viewing the category search results page
	**When** an individual search result is clicked
	**Then** I am presented with the page showing that particular review

## Tasks
- [x] add a category menu button to the navbar template
- [x] add a drop down menu that polls that database for the currently used categories for book reviews
- [x] create a search results page that displays all book reviews in a certain genre/category based on which button was clicked
- [x] link each search result to the page displaying an individual review
