### ISSUE TITLE
USER STORY: Admin area data formatting

### ISSUE THREAD

**Issue by neil314159** [neil314159/portfolio-project-4#32]
As a **site owner**, I can **log into the admin area and see all comments, reviews and wishlists**, so that **I can monitor the overall operation of the site and keep an overview of all content posted**

## Acceptance Criteria
- Acceptance Criteria 1
	**Given** that I am a site owner logged into the admin area
	**When** the comments, reviews or wishlist sections are selected
	**Then** I will see properly formatted data for each area
- Acceptance Criteria 2
	**Given** that I select a model from the admin panel
	**When** search and filter panels are used
	**Then** I can display the appropriate results in table form

## Tasks
- [x] make sure all models have been linked to the admin page
- [x] format the models to return useful strings as identifiers
- [ ] add search and filtering panels to the admin layout

**Comment by neil314159** [comment]
Main models were added to data admin area but further formatting of presentation is possible
