### ISSUE TITLE
USER STORY: Book review of the week

### ISSUE THREAD

**Issue by neil314159** [neil314159/portfolio-project-4#34]
As a **site owner**, I can **select a book review to be highlighted on the main home page**, so that **high quality content is presented to new users**

## Acceptance Criteria
- Acceptance Criteria 1
	**Given** that I log into the site as an administrator
	**When** I view individual book reviews
	**Then** I will see a button which allows me to select the book as "Book of the week"
- Acceptance Criteria 2
	**Given** that I have selected a book of the week
	**When** the button has been clicked
	**Then** the home page is updated to display this book review in a hero section at the top of the page
- Acceptance Criteria 3
	**Given** that previously a different book of the week was selected
	**When** a new book is chosen
	**Then** the previous book is removed from the home page and the new book added

## Tasks
- [ ] update the review model with a boolean to denote book of the week
- [ ] create a static home page template
- [ ] add a hero section with a link to the currently selected book of the week
- [ ] if no book is selected then default to the review with the most likes
- [ ] add logic to remove flag from previous book and apply to the new selection
