### ISSUE TITLE
USER STORY: Automated test suite

### ISSUE THREAD

**Issue by neil314159** [neil314159/portfolio-project-4#35]
As a **developer**, I want **to deploy automated testing with high code coverage**, so that **I can reduce the number of bugs in the site and improve the user experience**

## Acceptance Criteria
- Acceptance Criteria 1
	**Given** that each app within the site is covered by test cases
	**When** the test suite is run
	**Then** the code should be free of errors and have a high degree of coverage

## Tasks
- [ ] For each app within the site develop a full set of tests to test each aspect of the code
- [x] Download and install coverage tool
- [x] Run test and generate automatic report outlining what percentage of code is covered by testing
- [x] Include this report in the Readme file

**Comment by neil314159** [comment]
Testing was completed for models.py but not for views.py, models.py has 100% coverage, overall total coverage is 89%
