### ISSUE TITLE
USER STORY: Manual testing

### ISSUE THREAD

**Issue by neil314159** [neil314159/portfolio-project-4#36]
As a **developer**, I want to **manually test every aspect of the interface and functionality of the site**, so that **users can have a bug-free and consistent experience **

## Tasks
- [x] create a spreadsheet outlining every area of the site and a list of steps to manually test each one
- [x] record the results of the tests and make note of any bugs to be fixed
- [x] make a note of the testing strategy in the Readme file
