### ISSUE TITLE
USER STORY: Third party testing

### ISSUE THREAD

**Issue by neil314159** [neil314159/portfolio-project-4#37]
As a **developer**, I can **ask an independent person to test out the site while I watch**, so that **note any bugs or any part of the interface which is not easily understood**

## Tasks
- [x] Enlist a person who has never used the site before
- [x] Ask them to register an account while I watch and make use of each part of the site
- [x] Make not of any aspects of the interface they struggle with or any bugs they encounter
- [x] incorporate this feedback into bug fixes
