### ISSUE TITLE
USER STORY: Code validation

### ISSUE THREAD

**Issue by neil314159** [neil314159/portfolio-project-4#38]
As a **developer**, I want **all of the code in the site to conform to best practices**, so that **it is clear, readable and bug-free**

## Tasks
- [x] submit all html to the W3C validator
- [x] run all JS code through the JShint validator
- [x] submit all python code to the pep8 checker
- [x] run the entire site through the WAVE accessibility checker
- [x] run the site through the google lighthouse checker and generate a report
