### ISSUE TITLE
USER STORY: Install and configure Bootstrap

### ISSUE THREAD

**Issue by neil314159** [neil314159/portfolio-project-4#39]
As a **developer**, I want **to use a flexible framework**, so that **the user interface of the site can be made consistent and usable **

## Acceptance Criteria
- Acceptance Criteria 1
	**Given** that I am a user visiting the site
	**When** the site is loaded
	**Then** the interface should be clear and composed of standard elements
- Acceptance Criteria 2
	**Given** that i am a user on the site
	**When** i carry out an action that requires a confirmation message to be displayed
	**Then** I see a message delivered in a consistent and appropriate format

## Tasks
- [x] add bootstrap headers to base templates
- [x] create a navbar with navigation elements
- [x] add bootstrap formatting to lay out pages and forms
- [x] connect bootstrap messages to django messaging system for user feedback
