### ISSUE TITLE
USER STORY: Night mode

### ISSUE THREAD

**Issue by neil314159** [neil314159/portfolio-project-4#40]
As a **user**, I can **select the choice between normal and dark mode**, so that **I can use the site with the colour scheme I prefer**

## Acceptance Criteria
- Acceptance Criteria 1
	**Given** that I visit the site as a user
	**When** the toggle switch is selected
	**Then** my preferred colour scheme is displayed
- Acceptance Criteria 2
	**Given** that the user is on a mobile phone or tablet
	**When** the toggle switch is selected
	**Then** the colour scheme changes to reflect the state of the switch as on the desktop

## Tasks
- [ ] add a light and dark colour scheme to the css file
- [ ] add a switch element to the navbar with a label for dark mode
- [ ] check the user profile for previous preferences to determine state of switch
- [ ] check that the toggle works in desktop and mobile mode
