### ISSUE TITLE
USER STORY: Responsive layout on different devices

### ISSUE THREAD

**Issue by neil314159** [neil314159/portfolio-project-4#41]
As a **user**, I want **to have the site be responsive across different devices**, so that **I can enjoy a consistent experience and access the site from laptop, phone or tablet**

## Acceptance Criteria
- Acceptance Criteria 1
	**Given** that I am accessing the site from a desktop computer
	**When** the site appears on my screen
	**Then** it should be sized and formatted to match my device
- Acceptance Criteria 2
	**Given** that I am displaying the site on a tablet device
	**When** the site appears on the screen
	**Then** it should have appropriate font sizes and layouts to match the device resolution
- Acceptance Criteria 3
	**Given** that I am accessing the site from a mobile phone
	**When** the site is displayed
	**Then** it should be formatted correctly for my device and remain readable and usable

## Tasks
- [x] make sure all html templates are using bootstrap framework
- [x] check breakpoints to ensure that the content is resized at appropriate resolutions
- [x] use bootstrap layout tags to create layouts for desktops, tablets and phones
- [x] check the site using developer tools simulator across a wide range of resolutions
