### ISSUE TITLE
USER STORY: Form styling

### ISSUE THREAD

**Issue by neil314159** [neil314159/portfolio-project-4#42]
As a **site owner**, I want **all forms on the site to be styled in a similar fashion **, so that **the user interface is  consistent across the whole site**

## Acceptance Criteria
- Acceptance Criteria 1
	**Given** that I am user on the site
	**When** I access any of the forms to create, edit and delete an account or any content on the site
	**Then** the forms I use are consistent in styling and layout

## Tasks
- [x] install and configure crispy forms software package
- [x] add to dependencies
- [x] integrate crispy form tags into each form on the site
- [x] carry out any further styling required using bootstrap
