### ISSUE TITLE
USER STORY: Accessibilty

### ISSUE THREAD

**Issue by neil314159** [neil314159/portfolio-project-4#43]
As a **user**, I can **make use of accessibility features on the site**, so that **I can navigate and use the site without difficulty**

## Acceptance Criteria
- Acceptance Criteria 1
	**Given** that I am using a screen reader
	**When** the site is accessed
	**Then** each element on the site should be clear and navigable
- Acceptance Criteria 2
	**Given** that I am a vision-impaired user
	**When** the user interface is presented to me
	**Then** it is highly legible and does not have low-contrast graphics

## Tasks
- [x] Use the WAVE accessibility checker tool to determine any aspects of the site that are low contrast or unreadable for vision-impaired users
- [x] use appropriate aria-tags throughout to ensure screen readers can parse the site
- [x] use semantic tags elsewhere to make sure all content is labelled
