### ISSUE TITLE
USER STORY: User feedback messages

### ISSUE THREAD

**Issue by neil314159** [neil314159/portfolio-project-4#44]
As a **user**, I can **receive clear and unambiguous feedback about my actions**, so that **I can be sure that each operation was carried out successfully**

## Acceptance Criteria
- Acceptance Criteria 1
	**Given** that I am a user on the site
	**When** I edit or delete a review or comment
	**Then** I will see a message displayed on the site informing that the operation was carried out
- Acceptance Criteria 2
	**Given** that i am a user on the site
	**When** a database or API call is unsuccessful
	**Then** I will receive a feedback message on the site notifying me of this

## Tasks
- [x] add messages queue to the templates used in the site
- [x] check bootstrap integration with django messaging function
- [x] use javascript to set visibility timeout function
- [x] add try catch blocks to API calls and warn users if an operation has failed
