### ISSUE TITLE
USER STORY: Display reviews

### ISSUE THREAD

**Issue by neil314159** [neil314159/portfolio-project-4#47]
As a **user**, I can **view articles reviewing books on the site**, so that **I can learn about new books I might like to read**

## Acceptance Criteria
- Acceptance Criteria 1
	**Given** that I am user on the site
	**When** I click on a book review link from the main page
	**Then** I am presented with a single page showing all details of the review

## Tasks
- [x] create a page displaying all book reviews on the site
- [x] implement pagination for this page
- [x] make sure articles are displayed for users who are logged in or not
- [x] create a html element showing the book cover, star rating, title and author and use this for displaying lists of reviews
