### ISSUE TITLE
USER STORY: Delete reviews

### ISSUE THREAD

**Issue by neil314159** [neil314159/portfolio-project-4#48]
As a **user**, I can **delete a review that I have written**, so that **it is removed from the site**

## Acceptance Criteria
- Acceptance Criteria 1
	**Given** that I am a registered or unregistered user
	**When** I view an article that I did not write
	**Then** there will be no button to delete the article shown
- Acceptance Criteria 2
	**Given** that I am registered and logged in user
	**When** I view an article that I created
	**Then** I will see a button to delete the article
- Acceptance Criteria 3
	**Given** that I have clicked the delete button on my article
        **Then** I am shown a form to confirm that I wish to delete the article
	**When** the confirm button is pressed
	**Then** the article is removed from the database and the site
- Acceptance Criteria 4
	**Given** that I am registered and logged in user
	**When** I attempt to delete another users article by following the URL path
	**Then** I will be redirected to the home page

## Tasks
- [x] add a delete button to the review page for logged in users viewing their own content
- [x] add a confirmation form which double checks the user wishes to delete the article
- [x] remove the article form the database after checking that the user has the appropriate permissions
