### ISSUE TITLE
USER STORY: Book cover image

### ISSUE THREAD

**Issue by neil314159** [neil314159/portfolio-project-4#49]
As a **user**, I can **upload a cover image for the book review**, so that **the book cover can be shown on the site when users browse or search for reviews**

## Acceptance Criteria
- Acceptance Criteria 1
	**Given** that I am logged in and registered on the site
	**When** I am creating a review
	**Then** I will see a field to upload an image for the book cover
- Acceptance Criteria 2
	**Given** that I have written a book review on the site
	**When** I do not upload an accompanying cover
	**Then** a default image is provided

## Tasks
- [x] link cloudinary API in the templates and setting files
- [x] resize the image to appropriate dimensions and ration before using
- [x] add a default cover if no image is uploaded
