### ISSUE TITLE
USER STORY: Book cover API

### ISSUE THREAD

**Issue by neil314159** [neil314159/portfolio-project-4#50]
As a **user**, I can **search books by title**, so that **a book cover image is automatically found and added to my review**

## Acceptance Criteria
- Acceptance Criteria 1
	**Given** that I am a user creating a review on the site
	**When** the title of the book is typed in
	**Then** I am shown a list of matching titles that I can select from to upload a cover image for my review
- Acceptance Criteria 2
	**Given** that I have selected an image from the search results list
	**When** the image is clicked on
	**Then** it is added to the form field for the book cover and saved in the database

## Tasks
- [ ] connect to google books or open library API
- [ ] create AJAX search field for book title
- [ ] create a results list that allows the user to select their book
- [ ] validate the image returned by the API and save in the database
