### ISSUE TITLE
USER STORY: AJAX category editing

### ISSUE THREAD

**Issue by neil314159** [neil314159/portfolio-project-4#51]
As a **user**, I can **create a new category when writing a review**, so that **my article is published under the most suitable genre**

## Acceptance Criteria
- Acceptance Criteria 1
	**Given** that I am a registered and logged in user
	**When** I am creating a review on the site
	**Then** if a suitable category is not available then I may add one to the database through a form field
- Acceptance Criteria 2
	**Given** that i have added a new category for my book review
	**When** the category is selected for my review
	**Then** the article is correctly categorised and the category is added to the drop-down menu in the navbar

## Tasks
- [ ] add AJAX field to the review creation form
- [ ] add code to create a new category and fill this in as the selected option
- [ ] validate the form input to ensure the new category is not too short/contains invalid characters
